### ISSUE TITLE
请问一下你的嵌套评论的后端数据库是怎么设计的

### ISSUE THREAD

**Issue by ddgweb** [TommyLemon/APIJSON-Android-RxJava#1]
想学习一下你的数据库设计思路

**Comment by TommyLemon** [comment]
单表，toId 指向父评论，然后用算法处理 
https://github.com/APIJSON/AbsGrade

**Comment by ddgweb** [comment]
> 单表，toId 指向父评论，然后用算法处理
> https://github.com/APIJSON/AbsGrade

能否给一个你的Demo数据库结构sql，学习一下

**Comment by TommyLemon** [comment]
https://github.com/APIJSON/APIJSON/tree/master/MySQL
